// Predefined errors

export const WRONG_REQUEST = 'WRONG_REQUEST'
export const INTERNAL_ERROR = 'INTERNAL_ERROR'
export const FORBIDDEN = 'FORBIDDEN'
export const VALIDATION_ERROR = 'VALIDATION_ERROR'
export const NOT_FOUND = 'NOT_FOUND'
export const WRONG_LOGIN_OR_PASSWORD = 'WRONG_LOGIN_OR_PASSWORD'
export const EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE'
export const EMAIL_IS_NOT_CONFIRMED = 'EMAIL_IS_NOT_CONFIRMED'
export const UNAUTHORIZED = 'UNAUTHORIZED'
